/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc721Sol from "./IERC721.sol";
export type { ierc721Sol };
export type { INFTCollection1155 } from "./INFTCollection1155";
export type { INFTFactory } from "./INFTFactory";
