/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
// import type * as ierc721Sol from "./IERC721.sol";
export type { INFTCollection721 } from "./INFTCollection721";
export type { INFTCollection1155 } from "./INFTCollection1155";
export type { INFTFactory } from "./INFTFactory";
