/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { NFTCollection1155 } from "./NFTCollection1155";
export type { NFTCollection721 } from "./NFTCollection721";
export type { NFTFactory } from "./NFTFactory";
